### ISSUE TITLE
Practica #2 - Costos

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/Software_Proyecto#5]
[Practica_2-CB-24h.pdf](https://github.com/SistemasTecTlaxiaco/Software_Proyecto/files/6157738/Practica_2-CB-24h.pdf)

**Comment by CarlosSD16** [comment]
le falta agregar mas imágenes para cumplir lo que marca la rubrica y así sea mas entendible el desarrollo de costos de su proyecto
